name: Build

on: [push]

env:
  PYTHON_VERSION: 3.13

jobs:
  build-binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4.2.2
      - uses: actions/setup-python@5.3.0
        with:
          python-version: $PYTHON_VERSION
      - run: python -m pip install build
      - run: python -m build
