name: Build

on: [push]

env:
  PYTHON_VERSION: 3.13
  ACTIONS_RUNNER_DEBUG: true

jobs:
  build-binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-python@v5.3.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - run: python -m pip install build
      - run: python -m build
