name: Run linter

on: [push]

env:
  PYTHON_VERSION: 3.13
  RUFF_VERSION: 0.9.3

jobs:
  run-ruff-check:
    runs-on: gha-runner-scale-set
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-python@v5.3.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - run: pip install ruff==${{ env.RUFF_VERSION }}
      - run: ruff check
