name: Release package to PyPI

on:
  release:
    types: [published]

env:
  PYTHON_VERSION: 3.13

jobs:
  push-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-python@v5.3.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Build package
        run: python -m build

      - name: Prepare environment to push package
        run: |
          python -m pip install twine
          cat <<EOF > ~/.pypirc
          [testpypi]
            username = __token__
            password = ${{ secrets.TEST_PYPI_TOKEN }}
          EOF

      - name: Push package
        run: python -m twine upload --repository testpypi dist/*
